# Meta Data for SEO

## Homepage
title = "THE 100"
titleSeparator = "-"
titleAddition = "Tagline"
description = "Description"

## Documentation
docsVersion = "1.0"
the100Version = "1.0"

## Open Graph
images = ["tfd.png"]
ogLocale = "en_US"
domainTLD = "theforgetful.dev"
titleHome = "THE 100"

## Twitter Cards
twitterSite = "@user"
twitterCreator = "@user"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "THE100"
schemaAuthor = "THE 100"
schemaAuthorTwitter = "https://twitter.com/user"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/"
schemaAuthorGitHub = "https://github.com/nesb0t"
schemaLocale = "en-US"
schemaLogo = "logo-tfd.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "tfd.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/user"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/nesb0t"
schemaSection = "posts"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a> and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) The Forgeful Dev"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/h-enk/doks"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["the100"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = "ALL"
  #searchSectionsIndex = "docs"
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  the100Versioning = true
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = false
